spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               /opt/spark/logs
spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.driver.memory              2g
spark.executor.memory            2g
spark.executor.cores             2
spark.sql.shuffle.partitions     4
spark.default.parallelism        4
spark.hadoop.fs.defaultFS        hdfs://hadoop-namenode:9005
spark.python.worker.reuse        true
spark.sql.streaming.kafka.useDeprecatedOffsetFetching false
spark.sql.streaming.checkpointLocation /opt/spark/data/checkpoints